name: Build Client
on:
  push:
    branches:
      - "main"
    paths:
      - 'Source_Code/Client/*.cpp'
      - 'Source_Code/Client/*.h'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build libzmq & cppzmq
      run: |
        mkdir libs && cd libs
        git clone https://github.com/zeromq/libzmq.git && git clone https://github.com/zeromq/cppzmq.git
        cd libzmq
        mkdir build
        cd build
        cmake ..
        sudo make -j4 install
        cd ../../
        cd cppzmq
        mkdir build
        cd build
        cmake ..
        sudo make -j4 install
        cd
    - name: change .pro file
      run: | 
        cd Source_Code/Client
        echo "TEMPLATE = app
        CONFIG += console c++11
        CONFIG -= app_bundle
        CONFIG -= qt

        DEFINES += ZMQ_STATIC

        # Default rules for deployment.
        qnx: target.path = /tmp/\$\${TARGET}/bin
        else: unix:!android: target.path = /opt/\$\${TARGET}/bin
        !isEmpty(target.path): INSTALLS += target

        CONFIG += link_pkgconfig
        PKGCONFIG += cppzmq

        SOURCES += main.cpp \\
        client.cpp

        HEADERS += \\
        client.h" > Client.pro
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: Run qmake
      run: |
        mkdir Source_Code/build && cd Source_Code/build
        qmake -o Makefile ../Client/Client.pro
    - name: Run make
      run: cd Source_Code/build && make
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: Source_Code/build/Client
